# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Google Drive Principal\Facultate\Anul 3\Semestrul 1\Prelucrarea Imaginilor\Proiect\Aplicatie\interfata.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 779)
        MainWindow.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setStyleSheet("background-color:rgb(170, 170, 255);")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Photos = QtWidgets.QWidget()
        self.Photos.setObjectName("Photos")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Photos)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PhotosContent = QtWidgets.QWidget(self.Photos)
        self.PhotosContent.setObjectName("PhotosContent")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.PhotosContent)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.WhereIsPhoto = QtWidgets.QLabel(self.PhotosContent)
        self.WhereIsPhoto.setMinimumSize(QtCore.QSize(0, 600))
        self.WhereIsPhoto.setText("")
        self.WhereIsPhoto.setObjectName("WhereIsPhoto")
        self.verticalLayout_5.addWidget(self.WhereIsPhoto)
        self.CBsPhoto = QtWidgets.QWidget(self.PhotosContent)
        self.CBsPhoto.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CBsPhoto.setObjectName("CBsPhoto")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CBsPhoto)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.UploadPhotoCB = QtWidgets.QPushButton(self.CBsPhoto)
        self.UploadPhotoCB.setMinimumSize(QtCore.QSize(300, 50))
        self.UploadPhotoCB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UploadPhotoCB.setStyleSheet("QPushButton{\n"
"    background-color: rgb(199, 197, 255);\n"
"    border: 3px solid rgb(138, 138, 207);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 85, 255);\n"
"    border: 3px solid rgb(159, 79, 238);\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 0, 127);\n"
"\n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}")
        self.UploadPhotoCB.setObjectName("UploadPhotoCB")
        self.horizontalLayout.addWidget(self.UploadPhotoCB)
        self.RecognitionPhotoCB = QtWidgets.QPushButton(self.CBsPhoto)
        self.RecognitionPhotoCB.setMinimumSize(QtCore.QSize(300, 50))
        self.RecognitionPhotoCB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RecognitionPhotoCB.setStyleSheet("QPushButton{\n"
"    background-color: rgb(199, 197, 255);\n"
"    border: 3px solid rgb(138, 138, 207);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 85, 255);\n"
"    border: 3px solid rgb(159, 79, 238);\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 0, 127);\n"
"\n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}")
        self.RecognitionPhotoCB.setObjectName("RecognitionPhotoCB")
        self.horizontalLayout.addWidget(self.RecognitionPhotoCB)
        self.verticalLayout_5.addWidget(self.CBsPhoto)
        self.verticalLayout.addWidget(self.PhotosContent)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Google Drive Principal\\Facultate\\Anul 3\\Semestrul 1\\Prelucrarea Imaginilor\\Proiect\\Aplicatie\\../icons/icon-image-512.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Photos, icon, "")
        self.Videos = QtWidgets.QWidget()
        self.Videos.setObjectName("Videos")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Videos)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.VideosContent = QtWidgets.QWidget(self.Videos)
        self.VideosContent.setObjectName("VideosContent")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.VideosContent)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.WhereIsVideo = QtWidgets.QLabel(self.VideosContent)
        self.WhereIsVideo.setMinimumSize(QtCore.QSize(0, 600))
        self.WhereIsVideo.setText("")
        self.WhereIsVideo.setObjectName("WhereIsVideo")
        self.verticalLayout_6.addWidget(self.WhereIsVideo)
        self.CBsVideo = QtWidgets.QWidget(self.VideosContent)
        self.CBsVideo.setObjectName("CBsVideo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.CBsVideo)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.UploadVideoCB = QtWidgets.QPushButton(self.CBsVideo)
        self.UploadVideoCB.setMinimumSize(QtCore.QSize(300, 50))
        self.UploadVideoCB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UploadVideoCB.setStyleSheet("QPushButton{\n"
"    background-color: rgb(199, 197, 255);\n"
"    border: 3px solid rgb(138, 138, 207);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 85, 255);\n"
"    border: 3px solid rgb(159, 79, 238);\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 0, 127);\n"
"\n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}")
        self.UploadVideoCB.setObjectName("UploadVideoCB")
        self.horizontalLayout_2.addWidget(self.UploadVideoCB)
        self.RecognitionVideoCB = QtWidgets.QPushButton(self.CBsVideo)
        self.RecognitionVideoCB.setMinimumSize(QtCore.QSize(300, 50))
        self.RecognitionVideoCB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RecognitionVideoCB.setStyleSheet("QPushButton{\n"
"    background-color: rgb(199, 197, 255);\n"
"    border: 3px solid rgb(138, 138, 207);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 85, 255);\n"
"    border: 3px solid rgb(159, 79, 238);\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 0, 127);\n"
"\n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}")
        self.RecognitionVideoCB.setObjectName("RecognitionVideoCB")
        self.horizontalLayout_2.addWidget(self.RecognitionVideoCB)
        self.StopVideoCB = QtWidgets.QPushButton(self.CBsVideo)
        self.StopVideoCB.setMinimumSize(QtCore.QSize(300, 50))
        self.StopVideoCB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StopVideoCB.setStyleSheet("QPushButton{\n"
"    background-color: rgb(199, 197, 255);\n"
"    border: 3px solid rgb(138, 138, 207);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 85, 255);\n"
"    border: 3px solid rgb(159, 79, 238);\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 0, 127);\n"
"\n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}")
        self.StopVideoCB.setObjectName("StopVideoCB")
        self.horizontalLayout_2.addWidget(self.StopVideoCB)
        self.verticalLayout_6.addWidget(self.CBsVideo)
        self.verticalLayout_2.addWidget(self.VideosContent)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Google Drive Principal\\Facultate\\Anul 3\\Semestrul 1\\Prelucrarea Imaginilor\\Proiect\\Aplicatie\\../icons/video-icon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Videos, icon1, "")
        self.LiveCamera = QtWidgets.QWidget()
        self.LiveCamera.setObjectName("LiveCamera")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.LiveCamera)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LiveCameraContent = QtWidgets.QWidget(self.LiveCamera)
        self.LiveCameraContent.setObjectName("LiveCameraContent")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.LiveCameraContent)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.WhereIsCamera = QtWidgets.QLabel(self.LiveCameraContent)
        self.WhereIsCamera.setMinimumSize(QtCore.QSize(0, 600))
        self.WhereIsCamera.setText("")
        self.WhereIsCamera.setObjectName("WhereIsCamera")
        self.verticalLayout_7.addWidget(self.WhereIsCamera)
        self.CBsCamera = QtWidgets.QWidget(self.LiveCameraContent)
        self.CBsCamera.setObjectName("CBsCamera")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.CBsCamera)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StartCameraCB = QtWidgets.QPushButton(self.CBsCamera)
        self.StartCameraCB.setMinimumSize(QtCore.QSize(300, 50))
        self.StartCameraCB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartCameraCB.setStyleSheet("QPushButton{\n"
"    background-color: rgb(199, 197, 255);\n"
"    border: 3px solid rgb(138, 138, 207);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 85, 255);\n"
"    border: 3px solid rgb(159, 79, 238);\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 0, 127);\n"
"\n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}")
        self.StartCameraCB.setObjectName("StartCameraCB")
        self.horizontalLayout_3.addWidget(self.StartCameraCB)
        self.StopCameraCB = QtWidgets.QPushButton(self.CBsCamera)
        self.StopCameraCB.setMinimumSize(QtCore.QSize(300, 50))
        self.StopCameraCB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StopCameraCB.setStyleSheet("QPushButton{\n"
"    background-color: rgb(199, 197, 255);\n"
"    border: 3px solid rgb(138, 138, 207);\n"
"    border-radius: 20px;\n"
"    color: rgb(0, 0, 127);\n"
"    \n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(170, 85, 255);\n"
"    border: 3px solid rgb(159, 79, 238);\n"
"    border-radius: 20px;\n"
"    color: rgb(85, 0, 127);\n"
"\n"
"    font: 18pt \"Franklin Gothic Demi\";\n"
"}")
        self.StopCameraCB.setObjectName("StopCameraCB")
        self.horizontalLayout_3.addWidget(self.StopCameraCB)
        self.verticalLayout_7.addWidget(self.CBsCamera)
        self.verticalLayout_4.addWidget(self.LiveCameraContent)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\Google Drive Principal\\Facultate\\Anul 3\\Semestrul 1\\Prelucrarea Imaginilor\\Proiect\\Aplicatie\\../icons/83574.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.LiveCamera, icon2, "")
        self.Help = QtWidgets.QWidget()
        self.Help.setObjectName("Help")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Help)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.TitluHelp = QtWidgets.QTextBrowser(self.Help)
        self.TitluHelp.setMinimumSize(QtCore.QSize(0, 100))
        self.TitluHelp.setMaximumSize(QtCore.QSize(16777215, 100))
        self.TitluHelp.setStyleSheet("")
        self.TitluHelp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TitluHelp.setObjectName("TitluHelp")
        self.verticalLayout_8.addWidget(self.TitluHelp)
        self.ContentHelp = QtWidgets.QTextBrowser(self.Help)
        self.ContentHelp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ContentHelp.setObjectName("ContentHelp")
        self.verticalLayout_8.addWidget(self.ContentHelp)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\Google Drive Principal\\Facultate\\Anul 3\\Semestrul 1\\Prelucrarea Imaginilor\\Proiect\\Aplicatie\\../icons/3524335.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Help, icon3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionPhoto = QtWidgets.QAction(MainWindow)
        self.actionPhoto.setIcon(icon)
        self.actionPhoto.setObjectName("actionPhoto")
        self.actionVideo = QtWidgets.QAction(MainWindow)
        self.actionVideo.setIcon(icon1)
        self.actionVideo.setObjectName("actionVideo")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLive_Detection = QtWidgets.QAction(MainWindow)
        self.actionLive_Detection.setIcon(icon2)
        self.actionLive_Detection.setObjectName("actionLive_Detection")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UploadPhotoCB.setText(_translate("MainWindow", "Upload"))
        self.RecognitionPhotoCB.setText(_translate("MainWindow", "Recognition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Photos), _translate("MainWindow", "Photo"))
        self.UploadVideoCB.setText(_translate("MainWindow", "Upload"))
        self.RecognitionVideoCB.setText(_translate("MainWindow", "Recognition"))
        self.StopVideoCB.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Videos), _translate("MainWindow", "Video"))
        self.StartCameraCB.setText(_translate("MainWindow", "Start"))
        self.StopCameraCB.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LiveCamera), _translate("MainWindow", "Live Camera"))
        self.TitluHelp.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bodoni MT Poster Compressed\'; font-size:48pt; font-weight:600; text-decoration: underline;\">Help</span></p></body></html>"))
        self.ContentHelp.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Aplicația realizează recunoașterea facială </span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">dintr-o îregistrare video în timp real sau deja existentă și din imagini.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'sans-serif\'; font-size:16pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">Pentru a realiza recunoașterea facială dintr-o imagine se va apăsa pe butonul &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">Upload</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot; din tab-ul &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">Photo</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot;, se va selecta imaginea dorită și aceasta va fi încărcată în interfața aplicației, iar apoi, prin apăsarea butonului &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">Recognition</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot; se va realiza recunoașterea, apărând pe fețele oamenilor prezenți în imagine un chenar și numele lor, dacă există în sistem, sau &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">unknown</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot;, dacă nu îî recunoaște.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'sans-serif\'; font-size:16pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">Pentru a realiza recunoașterea facială dintr-o înregistrare deja existentă, în tab-ul &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">Video</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot; se va apăsa pe butonul &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">Upload</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot; se va selecta înregistrarea dorită, dar aceasta nu va fi încărcată în interfața aplicației. Prin apăsarea butonului &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">Recognition</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot; se va încărca înregistrarea în interfată și se va realiza, totodată, recunoașterea fețelor. Pentru a încărca o nouă înregistrare va trebui oprită cea precedentă, apăsând pe butonul &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">Stop</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot;, care o va opri.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'sans-serif\'; font-size:16pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">Pentru a realiza recunoașterea facială dintr-o înregistrare în timp real, în tab-ul &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">Live Camera</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot; se va apăsa pe butonul &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">Start</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot;, se va deschide camera, se va realiza recunoașterea fețelor și va fi creat un fișier excel în care va fi contorizat timpul în care o persoană este prezentă. Apăsând butonul &quot;</span><span style=\" font-family:\'sans-serif\'; font-size:16pt; font-style:italic;\">Stop</span><span style=\" font-family:\'sans-serif\'; font-size:16pt;\">&quot; se va opri înregistrarea și nu se va mai contoriza timpul.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Help), _translate("MainWindow", "Help"))
        self.actionPhoto.setText(_translate("MainWindow", "Photo Detection"))
        self.actionVideo.setText(_translate("MainWindow", "Video Detection"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionLive_Detection.setText(_translate("MainWindow", "Live Detection"))
